In [5]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [6]:
r = requests.get("https://statistics.byu.edu/faculty-directory")
soup = BeautifulSoup(r.text)

In [7]:
raw_links = soup.find_all("a")

In [8]:
links = [link['href'] for link in raw_links]

In [9]:
print(len(links))
links = list(set(links))
print(len(links))

153
84

In [10]:
final_links = [link for link in links if link.__contains__('statistics.byu.edu/directory')]

In [11]:
len(final_links)

28

In [ ]:
data_dict = {
    "name": [], 
    "title": [], 
    'website': [], 
    'phone': [], 
    'email': [], 
    'office': []
}

def safe_scrape(soup, tag, class_name):
    try:
        return soup.find(tag, {"class": class_name}).text.strip()
    except:
        return None

for link in final_links:
    print(link)
    directory = requests.get(link)
    soup = BeautifulSoup(directory.text)

    name = safe_scrape(soup, "h1", "EmployeePage-name")
    title = safe_scrape(soup, "div", "EmployeePage-jobTitle")
    website = safe_scrape(soup, "div", "EmployeePage-websiteLink")
    phone = safe_scrape(soup, "div", "EmployeePage-phoneNumber")
    email = safe_scrape(soup, "div", "EmployeePage-email")
    office = safe_scrape(soup, "div", "EmployeePage-address")

    data_dict['name'].append(name)
    data_dict['title'].append(title)
    data_dict['website'].append(website)
    data_dict['phone'].append(phone)
    data_dict['email'].append(email)
    data_dict['office'].append(office)

df = pd.DataFrame(data_dict)
df.head()

https://statistics.byu.edu/directory/heaton-matthew
https://statistics.byu.edu/directory/reese-shane
https://statistics.byu.edu/directory/richardson-robert
https://statistics.byu.edu/directory/sandholtz-nate
https://statistics.byu.edu/directory/page-garritt
https://statistics.byu.edu/directory/grimshaw-scott-d
https://statistics.byu.edu/directory/tolley-h-dennis
https://statistics.byu.edu/directory/fellingham-gilbert-w
https://statistics.byu.edu/directory/jared-fisher
https://statistics.byu.edu/directory/candace-berrett
https://statistics.byu.edu/directory/warr-richard
https://statistics.byu.edu/directory/christensen-michael
https://statistics.byu.edu/directory/nielsen-lynne
https://statistics.byu.edu/directory/dahl-david-b
https://statistics.byu.edu/directory/hartman-brian
https://statistics.byu.edu/directory/scott-del-t
https://statistics.byu.edu/directory/petersen-alex
https://statistics.byu.edu/directory/matthew-j-heiner
https://statistics.byu.edu/directory/blades-natalie-j
https://statistics.byu.edu/directory/white-philip
https://statistics.byu.edu/directory/rhodes-jake
https://statistics.byu.edu/directory/perrett-jamie
https://statistics.byu.edu/directory/snow-greg
https://statistics.byu.edu/directory/tass-shannon
https://statistics.byu.edu/directory/mcbride-zoe
https://statistics.byu.edu/directory/kerby-thomas
https://statistics.byu.edu/directory/christensen-william-f
https://statistics.byu.edu/directory/spencer-wadsworth

,name,title,website,phone,email,office
0,"Heaton, Matthew",Professor,Website: http://mheaton.byu.edu/,Phone: 801-422-7249,Email: mheaton@stat.byu.edu,Office: 2152E WVB
1,"Reese, Shane",President of Brigham Young University,NaN,NaN,NaN,NaN
2,"Richardson, Robert",Associate Professor,Website: http://richardson.byu.edu/,Phone: 801-422-3736,Email: richardson@stat.byu.edu,Office: 2186 WVB
3,"Sandholtz, Nathan",Assistant Professor,Website: http://sandholtz.byu.edu,801-422-9251,Email: nsandholtz@stat.byu.edu,Office: 2181 WVB
4,"Page, Garritt",Professor,Website: https://page.byu.edu,Phone: 801-422-7269,Email: page@stat.byu.edu,Office: 2184 WVB

In [51]:
import re

def clean_website(website):
    pattern = r"https?://\w+\.byu\.edu"
    try:
        results = re.search(pattern, website)
        return results[0]
    except:
        return None
    
df["cleaned_website"] = df.loc[:, "website"].apply(clean_website)
df.head()

,name,title,website,phone,email,office,cleaned_website
0,"Heaton, Matthew",Professor,Website: http://mheaton.byu.edu/,Phone: 801-422-7249,Email: mheaton@stat.byu.edu,Office: 2152E WVB,http://mheaton.byu.edu
1,"Reese, Shane",President of Brigham Young University,NaN,NaN,NaN,NaN,NaN
2,"Richardson, Robert",Associate Professor,Website: http://richardson.byu.edu/,Phone: 801-422-3736,Email: richardson@stat.byu.edu,Office: 2186 WVB,http://richardson.byu.edu
3,"Sandholtz, Nathan",Assistant Professor,Website: http://sandholtz.byu.edu,801-422-9251,Email: nsandholtz@stat.byu.edu,Office: 2181 WVB,http://sandholtz.byu.edu
4,"Page, Garritt",Professor,Website: https://page.byu.edu,Phone: 801-422-7269,Email: page@stat.byu.edu,Office: 2184 WVB,https://page.byu.edu

In [53]:
def clean_office(office):
    pattern = r"\d{4}[A-Z]? [A-Z]{2,5}"
    try:
        results = re.search(pattern, office)
        return results[0]
    except:
        return None
    
df['cleaned_office'] = df.loc[:, "office"].apply(clean_office)
df.head()

,name,title,website,phone,email,office,cleaned_website,cleaned_office
0,"Heaton, Matthew",Professor,Website: http://mheaton.byu.edu/,Phone: 801-422-7249,Email: mheaton@stat.byu.edu,Office: 2152E WVB,http://mheaton.byu.edu,2152E WVB
1,"Reese, Shane",President of Brigham Young University,NaN,NaN,NaN,NaN,NaN,NaN
2,"Richardson, Robert",Associate Professor,Website: http://richardson.byu.edu/,Phone: 801-422-3736,Email: richardson@stat.byu.edu,Office: 2186 WVB,http://richardson.byu.edu,2186 WVB
3,"Sandholtz, Nathan",Assistant Professor,Website: http://sandholtz.byu.edu,801-422-9251,Email: nsandholtz@stat.byu.edu,Office: 2181 WVB,http://sandholtz.byu.edu,2181 WVB
4,"Page, Garritt",Professor,Website: https://page.byu.edu,Phone: 801-422-7269,Email: page@stat.byu.edu,Office: 2184 WVB,https://page.byu.edu,2184 WVB